In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
df = pd.read_csv("Raw_Data/marketing_campaign.csv", sep="\t")

In [5]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [6]:
df.tail()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 2240
Columns: 29

In [8]:
file_size = os.path.getsize("Raw_Data/marketing_campaign.csv")

print("Dataset Size:", round(file_size/1024,2),"KB")

Dataset Size: 215.03 KB

In [9]:
print("File Type: CSV")

File Type: CSV

# Deliverable (Summary Table)

| Property     | Value           |
| ------------ | --------------- |
| Rows         | (Python output) |
| Columns      | (Python output) |
| File Type    | CSV             |
| Dataset Size | (Python output) |
| Encoding     | UTF-8           |

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [11]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [12]:
variable_table = pd.DataFrame({
    "Variable": df.columns,
    "Data Type": df.dtypes.values
})

variable_table

               Variable Data Type
0                    ID     int64
1            Year_Birth     int64
2             Education    object
3        Marital_Status    object
4                Income   float64
5               Kidhome     int64
6              Teenhome     int64
7           Dt_Customer    object
8               Recency     int64
9              MntWines     int64
10            MntFruits     int64
11      MntMeatProducts     int64
12      MntFishProducts     int64
13     MntSweetProducts     int64
14         MntGoldProds     int64
15    NumDealsPurchases     int64
16      NumWebPurchases     int64
17  NumCatalogPurchases     int64
18    NumStorePurchases     int64
19    NumWebVisitsMonth     int64
20         AcceptedCmp3     int64
21         AcceptedCmp4     int64
22         AcceptedCmp5     int64
23         AcceptedCmp1     int64
24         AcceptedCmp2     int64
25             Complain     int64
26        Z_CostContact     int64
27            Z_Revenue     int64
28             Response     int64

In [13]:
missing = df.isnull().sum()

percentage = (missing/len(df))*100

missing_table = pd.DataFrame({
    "Variable": df.columns,
    "Missing Values": missing.values,
    "Percentage": percentage.values
})

missing_table

               Variable  Missing Values  Percentage
0                    ID               0    0.000000
1            Year_Birth               0    0.000000
2             Education               0    0.000000
3        Marital_Status               0    0.000000
4                Income              24    1.071429
5               Kidhome               0    0.000000
6              Teenhome               0    0.000000
7           Dt_Customer               0    0.000000
8               Recency               0    0.000000
9              MntWines               0    0.000000
10            MntFruits               0    0.000000
11      MntMeatProducts               0    0.000000
12      MntFishProducts               0    0.000000
13     MntSweetProducts               0    0.000000
14         MntGoldProds               0    0.000000
15    NumDealsPurchases               0    0.000000
16      NumWebPurchases               0    0.000000
17  NumCatalogPurchases               0    0.000000
18    NumStorePurchases               0    0.000000
19    NumWebVisitsMonth               0    0.000000
20         AcceptedCmp3               0    0.000000
21         AcceptedCmp4               0    0.000000
22         AcceptedCmp5               0    0.000000
23         AcceptedCmp1               0    0.000000
24         AcceptedCmp2               0    0.000000
25             Complain               0    0.000000
26        Z_CostContact               0    0.000000
27            Z_Revenue               0    0.000000
28             Response               0    0.000000

In [14]:
missing_table[missing_table["Missing Values"]==0]

               Variable  Missing Values  Percentage
0                    ID               0         0.0
1            Year_Birth               0         0.0
2             Education               0         0.0
3        Marital_Status               0         0.0
5               Kidhome               0         0.0
6              Teenhome               0         0.0
7           Dt_Customer               0         0.0
8               Recency               0         0.0
9              MntWines               0         0.0
10            MntFruits               0         0.0
11      MntMeatProducts               0         0.0
12      MntFishProducts               0         0.0
13     MntSweetProducts               0         0.0
14         MntGoldProds               0         0.0
15    NumDealsPurchases               0         0.0
16      NumWebPurchases               0         0.0
17  NumCatalogPurchases               0         0.0
18    NumStorePurchases               0         0.0
19    NumWebVisitsMonth               0         0.0
20         AcceptedCmp3               0         0.0
21         AcceptedCmp4               0         0.0
22         AcceptedCmp5               0         0.0
23         AcceptedCmp1               0         0.0
24         AcceptedCmp2               0         0.0
25             Complain               0         0.0
26        Z_CostContact               0         0.0
27            Z_Revenue               0         0.0
28             Response               0         0.0

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df["ID"].duplicated().sum()

np.int64(0)

In [17]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [18]:
for col in df.select_dtypes(include="object"):
    print("\n",col)
    print(df[col].unique())

 Education
['Graduation' 'PhD' 'Master' 'Basic' '2n Cycle']

 Marital_Status
['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'YOLO']

 Dt_Customer
['04-09-2012' '08-03-2014' '21-08-2013' '10-02-2014' '19-01-2014'
 '09-09-2013' '13-11-2012' '08-05-2013' '06-06-2013' '13-03-2014'
 '15-11-2013' '10-10-2012' '24-11-2012' '24-12-2012' '31-08-2012'
 '28-03-2013' '03-11-2012' '08-08-2012' '06-01-2013' '23-12-2012'
 '11-01-2014' '18-03-2013' '02-01-2013' '27-05-2013' '20-02-2013'
 '31-05-2013' '22-11-2013' '22-05-2014' '11-05-2013' '29-10-2012'
 '29-08-2013' '31-12-2013' '02-09-2013' '11-02-2014' '01-02-2013'
 '29-04-2013' '12-03-2013' '05-11-2013' '02-10-2013' '28-06-2014'
 '09-11-2012' '24-05-2013' '01-01-2014' '08-11-2012' '12-05-2014'
 '11-08-2012' '07-06-2014' '12-06-2013' '19-11-2012' '02-04-2013'
 '28-04-2014' '17-06-2013' '03-03-2014' '04-07-2013' '07-09-2012'
 '18-02-2013' '11-06-2013' '06-12-2013' '21-05-2013' '11-05-2014'
 '19-03-2014' '27-09-2013' '08-04-2013' '11-09-2012' '14-09-2012'
 '17-03-2013' '05-04-2013' '30-04-2014' '19-12-2012' '27-08-2012'
 '12-10-2012' '04-09-2013' '29-08-2012' '23-06-2013' '03-07-2013'
 '25-02-2014' '11-08-2013' '16-07-2013' '28-05-2014' '21-01-2014'
 '27-05-2014' '23-11-2013' '23-03-2014' '24-05-2014' '22-11-2012'
 '11-04-2013' '01-12-2013' '20-06-2013' '23-07-2013' '30-03-2014'
 '20-04-2013' '17-05-2013' '08-05-2014' '10-12-2013' '24-09-2013'
 '02-02-2013' '07-12-2012' '02-11-2013' '10-11-2012' '25-06-2014'
 '12-12-2012' '10-09-2013' '24-01-2014' '19-02-2013' '11-07-2013'
 '14-11-2013' '24-02-2014' '22-04-2013' '21-04-2013' '08-06-2014'
 '10-05-2014' '30-09-2013' '10-03-2013' '14-08-2013' '07-07-2013'
 '19-05-2014' '28-07-2013' '19-10-2012' '19-04-2013' '28-08-2013'
 '19-03-2013' '18-10-2012' '28-10-2012' '22-08-2012' '21-06-2014'
 '24-04-2014' '07-03-2014' '14-12-2012' '09-10-2012' '08-07-2013'
 '12-09-2013' '17-10-2013' '20-08-2013' '01-07-2013' '05-11-2012'
 '05-01-2014' '01-05-2013' '01-03-2014' '13-11-2013' '18-11-2013'
 '21-04-2014' '13-07-2013' '30-01-2014' '04-04-2014' '12-09-2012'
 '16-12-2012' '23-05-2014' '24-06-2014' '28-09-2013' '22-01-2014'
 '15-06-2014' '05-12-2012' '02-08-2013' '23-02-2013' '09-09-2012'
 '26-09-2013' '30-05-2013' '29-12-2013' '13-05-2014' '19-09-2013'
 '17-01-2013' '31-03-2014' '29-06-2014' '09-12-2013' '14-10-2013'
 '02-11-2012' '17-07-2013' '08-12-2013' '13-05-2013' '10-09-2012'
 '31-03-2013' '18-03-2014' '05-10-2012' '21-01-2013' '04-05-2013'
 '01-04-2014' '31-08-2013' '14-11-2012' '11-04-2014' '14-04-2014'
 '05-01-2013' '08-09-2012' '26-03-2013' '25-10-2012' '09-12-2012'
 '16-02-2014' '20-03-2013' '15-05-2013' '16-04-2014' '23-03-2013'
 '04-12-2013' '04-10-2013' '26-12-2013' '17-05-2014' '28-10-2013'
 '31-07-2013' '28-11-2013' '17-08-2012' '05-06-2014' '20-05-2013'
 '09-01-2013' '16-09-2013' '27-10-2013' '22-09-2012' '13-10-2012'
 '16-10-2012' '22-10-2012' '04-06-2013' '22-05-2013' '17-06-2014'
 '23-11-2012' '03-02-2013' '14-03-2013' '26-06-2014' '15-10-2012'
 '19-06-2013' '20-03-2014' '04-02-2014' '06-04-2014' '06-02-2013'
 '11-02-2013' '17-04-2014' '12-07-2013' '29-01-2013' '08-01-2013'
 '13-06-2013' '27-12-2013' '31-10-2012' '15-01-2014' '23-08-2012'
 '07-03-2013' '13-01-2013' '12-01-2013' '17-03-2014' '12-10-2013'
 '13-04-2014' '18-09-2012' '05-03-2014' '27-04-2013' '18-01-2014'
 '03-06-2013' '17-12-2013' '11-03-2014' '29-07-2013' '14-08-2012'
 '23-08-2013' '09-02-2014' '07-02-2013' '11-01-2013' '05-07-2013'
 '02-07-2013' '07-11-2013' '09-05-2013' '13-02-2013' '16-04-2013'
 '11-09-2013' '03-04-2013' '10-01-2013' '30-06-2013' '06-12-2012'
 '12-11-2012' '03-03-2013' '10-08-2012' '07-12-2013' '15-08-2013'
 '10-11-2013' '16-06-2014' '25-12-2012' '03-01-2014' '27-10-2012'
 '22-12-2012' '29-11-2013' '08-10-2013' '28-09-2012' '22-03-2014'
 '28-12-2012' '21-08-2012' '16-03-2013' '17-11-2012' '01-12-2012'
 '22-04-2014' '11-11-2012' '22-06-2013' '18-08-2012' '30-12-2012'
 '14-06-2013' '16-10-2013' '30-08-2012' '04-05-2014' '18-04-2013'
 '06-10-2013' '15-09-2012' '27-09-2012' '11-03-2013' '22-10-2013'
 '09-06-2014' '30-05-2014' '17-10-2012' '30-03-2013' '23-01-2013'
 '20-11-2013' '14-02-2014' '22-02-2013' '05-03-2013' '06-05-2014'
 '13-04-2013' '05-04-2014' '25-04-2013' '25-11-2013' '02-02-2014'
 '21-06-2013' '21-12-2013' '07-09-2013' '22-08-2013' '20-12-2013'
 '06-08-2013' '09-10-2013' '09-06-2013' '22-12-2013' '02-05-2013'
 '16-02-2013' '20-08-2012' '01-04-2013' '25-05-2014' '25-09-2012'
 '22-09-2013' '28-01-2014' '23-04-2013' '06-03-2014' '15-08-2012'
 '27-03-2013' '10-10-2013' '04-08-2012' '18-05-2014' '09-05-2014'
 '23-10-2012' '30-12-2013' '19-08-2012' '30-10-2013' '26-06-2013'
 '26-01-2014' '24-09-2012' '03-12-2012' '27-11-2013' '06-08-2012'
 '29-12-2012' '24-08-2012' '07-11-2012' '02-12-2013' '19-07-2013'
 '25-05-2013' '20-10-2013' '14-04-2013' '27-01-2014' '16-08-2013'
 '30-09-2012' '04-12-2012' '12-08-2012' '03-11-2013' '15-02-2013'
 '18-09-2013' '18-06-2014' '24-04-2013' '15-02-2014' '08-08-2013'
 '23-12-2013' '28-11-2012' '07-08-2013' '07-01-2014' '03-12-2013'
 '29-03-2014' '08-04-2014' '07-02-2014' '06-11-2013' '01-03-2013'
 '03-08-2013' '16-06-2013' '25-06-2013' '13-09-2013' '01-08-2013'
 '31-01-2013' '09-07-2013' '15-04-2013' '03-04-2014' '18-04-2014'
 '23-09-2012' '14-09-2013' '26-10-2012' '19-10-2013' '21-02-2013'
 '17-09-2013' '26-01-2013' '07-05-2014' '19-08-2013' '18-07-2013'
 '11-12-2012' '26-07-2013' '06-05-2013' '14-07-2013' '10-03-2014'
 '28-12-2013' '20-01-2013' '21-09-2012' '06-09-2012' '18-12-2012'
 '19-11-2013' '13-06-2014' '07-05-2013' '18-08-2013' '13-12-2013'
 '17-02-2014' '03-08-2012' '04-01-2014' '21-10-2013' '25-12-2013'
 '01-01-2013' '16-05-2013' '25-09-2013' '08-11-2013' '16-12-2013'
 '30-10-2012' '02-01-2014' '18-10-2013' '25-07-2013' '24-10-2013'
 '19-12-2013' '16-05-2014' '04-10-2012' '25-08-2013' '29-05-2013'
 '26-03-2014' '09-04-2014' '12-03-2014' '29-04-2014' '27-06-2014'
 '10-04-2013' '21-11-2013' '21-10-2012' '14-05-2013' '01-08-2012'
 '25-01-2014' '11-10-2013' '07-08-2012' '29-03-2013' '03-06-2014'
 '09-08-2012' '06-03-2013' '12-05-2013' '09-03-2014' '15-09-2013'
 '29-01-2014' '03-10-2013' '28-02-2013' '02-05-2014' '09-02-2013'
 '15-03-2013' '10-05-2013' '05-09-2012' '01-09-2013' '26-05-2013'
 '12-12-2013' '08-12-2012' '30-08-2013' '18-12-2013' '18-06-2013'
 '29-05-2014' '15-01-2013' '29-10-2013' '02-03-2013' '14-12-2013'
 '19-01-2013' '06-04-2013' '04-11-2013' '22-03-2013' '31-05-2014'
 '04-02-2013' '05-05-2013' '14-02-2013' '21-03-2014' '05-08-2013'
 '29-11-2012' '27-07-2013' '13-01-2014' '29-09-2012' '23-10-2013'
 '06-11-2012' '26-05-2014' '04-03-2014' '06-01-2014' '11-06-2014'
 '19-06-2014' '26-11-2012' '11-12-2013' '14-01-2014' '23-01-2014'
 '24-03-2013' '29-06-2013' '25-01-2013' '17-11-2013' '18-05-2013'
 '17-04-2013' '24-01-2013' '09-08-2013' '10-06-2013' '20-07-2013'
 '28-05-2013' '04-03-2013' '01-10-2012' '10-02-2013' '14-10-2012'
 '03-02-2014' '22-06-2014' '25-10-2013' '18-02-2014' '09-11-2013'
 '13-08-2013' '25-08-2012' '19-04-2014' '07-04-2014' '03-01-2013'
 '04-11-2012' '22-01-2013' '26-02-2014' '23-04-2014' '30-07-2013'
 '13-10-2013' '27-11-2012' '01-05-2014' '30-11-2012' '17-08-2013'
 '04-01-2013' '03-05-2014' '26-04-2014' '02-06-2014' '26-10-2013'
 '24-03-2014' '25-02-2013' '20-09-2013' '16-01-2013' '24-12-2013'
 '18-11-2012' '05-08-2012' '03-05-2013' '12-11-2013' '06-07-2013'
 '21-07-2013' '20-10-2012' '23-05-2013' '26-08-2012' '12-01-2014'
 '13-02-2014' '27-02-2014' '20-04-2014' '28-06-2013' '28-04-2013'
 '21-03-2013' '27-08-2013' '30-07-2012' '05-12-2013' '08-02-2013'
 '21-11-2012' '26-02-2013' '20-09-2012' '08-06-2013' '05-09-2013'
 '12-04-2014' '24-06-2013' '19-02-2014' '27-12-2012' '01-11-2012'
 '22-07-2013' '31-01-2014' '26-08-2013' '01-10-2013' '10-06-2014'
 '01-02-2014' '03-09-2012' '26-09-2012' '31-07-2012' '02-12-2012'
 '05-05-2014' '06-10-2012' '02-03-2014' '15-05-2014' '10-12-2012'
 '13-08-2012' '23-02-2014' '16-03-2014' '21-09-2013' '24-10-2012'
 '15-10-2013' '17-02-2013' '28-08-2012' '12-02-2014' '08-02-2014'
 '01-09-2012' '16-11-2012' '12-02-2013' '02-08-2012' '16-08-2012'
 '25-11-2012' '27-04-2014' '30-04-2013' '20-11-2012' '14-06-2014'
 '28-03-2014' '08-03-2013' '02-09-2012' '15-04-2014' '25-04-2014'
 '27-06-2013' '01-06-2013' '05-10-2013' '22-02-2014' '12-04-2013'
 '23-09-2013' '24-07-2013' '23-06-2014' '10-01-2014' '25-03-2013'
 '17-01-2014' '04-06-2014' '25-03-2014' '31-12-2012' '19-09-2012'
 '27-02-2013' '02-10-2012' '09-04-2013' '02-04-2014' '07-01-2013'
 '26-11-2013' '04-08-2013' '17-12-2012' '06-06-2014' '19-05-2013'
 '12-08-2013' '15-12-2013' '07-10-2012' '06-09-2013' '15-07-2013'
 '27-01-2013' '05-02-2014' '26-12-2012' '06-02-2014' '14-01-2013'
 '20-06-2014' '24-08-2013' '28-02-2014' '07-04-2013' '10-04-2014'
 '12-06-2014' '30-11-2013' '09-03-2013' '27-03-2014' '15-12-2012'
 '17-09-2012' '02-06-2013' '21-12-2012' '01-11-2013' '10-08-2013'
 '11-10-2012' '20-12-2012' '09-01-2014']

In [19]:
num_cols = df.select_dtypes(include=np.number).columns

num_cols

Index(['ID', 'Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Recency',
       'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts',
       'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
       'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
       'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5',
       'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact',
       'Z_Revenue', 'Response'],
      dtype='object')

In [20]:
summary = pd.DataFrame({
    "Minimum": df[num_cols].min(),
    "Maximum": df[num_cols].max(),
    "Mean": df[num_cols].mean()
})

summary

                     Minimum   Maximum          Mean
ID                       0.0   11191.0   5592.159821
Year_Birth            1893.0    1996.0   1968.805804
Income                1730.0  666666.0  52247.251354
Kidhome                  0.0       2.0      0.444196
Teenhome                 0.0       2.0      0.506250
Recency                  0.0      99.0     49.109375
MntWines                 0.0    1493.0    303.935714
MntFruits                0.0     199.0     26.302232
MntMeatProducts          0.0    1725.0    166.950000
MntFishProducts          0.0     259.0     37.525446
MntSweetProducts         0.0     263.0     27.062946
MntGoldProds             0.0     362.0     44.021875
NumDealsPurchases        0.0      15.0      2.325000
NumWebPurchases          0.0      27.0      4.084821
NumCatalogPurchases      0.0      28.0      2.662054
NumStorePurchases        0.0      13.0      5.790179
NumWebVisitsMonth        0.0      20.0      5.316518
AcceptedCmp3             0.0       1.0      0.072768
AcceptedCmp4             0.0       1.0      0.074554
AcceptedCmp5             0.0       1.0      0.072768
AcceptedCmp1             0.0       1.0      0.064286
AcceptedCmp2             0.0       1.0      0.013393
Complain                 0.0       1.0      0.009375
Z_CostContact            3.0       3.0      3.000000
Z_Revenue               11.0      11.0     11.000000
Response                 0.0       1.0      0.149107

In [21]:
cat_cols = df.select_dtypes(include="object").columns

cat_cols

Index(['Education', 'Marital_Status', 'Dt_Customer'], dtype='object')

In [22]:
for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

Education
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

Marital_Status
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

Dt_Customer
Dt_Customer
31-08-2012    12
12-09-2012    11
14-02-2013    11
12-05-2014    11
20-08-2013    10
              ..
05-08-2012     1
18-11-2012     1
25-05-2013     1
14-04-2013     1
09-01-2014     1
Name: count, Length: 663, dtype: int64

# Business Understanding (Task 10)

High Income Customers: Customers with higher annual income who are more likely to purchase premium products.
Frequent Buyers: Customers who make purchases regularly and contribute significantly to revenue.
Campaign Responders: Customers who accepted previous marketing campaigns.
Customers with Complaints: Customers who submitted complaints and may require better customer service.
Website Visitors: Customers who frequently visit the company's website, showing higher engagement.
High Spending Customers: Customers with large total spending across product categories.
Recently Active Customers: Customers with low recency values, indicating they purchased recently.